### ISSUE TITLE
感觉有点问题（不懂就问）

### ISSUE THREAD

**Issue by aclihub** [gameprestige/misaka#1]
![1](https://user-images.githubusercontent.com/54567707/63740921-7d6e3d80-c8c5-11e9-96bc-586a90c40975.png)
![2](https://user-images.githubusercontent.com/54567707/63740923-7e06d400-c8c5-11e9-8ff7-54a436655457.png)

**Comment by huandu** [comment]
这个实现里面，具体计算确实是分布式的落在每一个 misaka 节点上面的，不过确实限于技术和时间没有做到每个 misaka 之间直连，导致所有消息需要 last order 中转和总控，没有达到设计目标。

可惜后来停止开发了，所以也就半途而废了。

**Comment by aclihub** [comment]
不过您有过这个有趣的计划也还是让我很佩服的
