### ISSUE TITLE
Is this already died?

### ISSUE THREAD

**Issue by misaka19465** [gameprestige/misaka#2]
上一次commit是15年的，这都死了多少年了，明明初衷还不错(至少比我的[misakaNet](https://github.com/OlddoctorDevTeam/misakaNet)好)

**Comment by huandu** [comment]
哈哈哈哈哈，抱歉，确实不维护了。

这个项目是当时公司（Game Prestige）内部使用的，公司暂停业务后公开了内部用的一些系统（当然去掉了业务相关的部分），所以后续也没有更新维护了。Hubot + Slack 曾一度非常火，当时基于这个背景搞了一套系统，不过后来在其他公司也没有用到的地方，于是也就没有维护了。

你有什么好想法么？如果有一些需求，我也很乐意一起参与下，贡献下想法、设计甚至代码。

**Comment by sfc9982** [comment]
也比我的MisakaNetwork好
